name: Pipeline for Library-retake-exam app 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-an-unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
<<<<<<< HEAD
      uses: actions/setup-node@v4
=======
      uses: actions/setup-node@v3
>>>>>>> a35d68e9d49444f43f99f06876ef8687bc26e84b
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Checkout the repository 
      run: npm install 
    - name: Run Unit tests 
      run: npm run test:unit
    - name: Show my username
      run: echo "username - ssllaavv"
